flags: {}
extra-package-dbs: []
packages:
- .
- location:
      git: https://github.com/agrafix/Spock.git
      commit: 77333a2de5dea0dc8eba9432ab16864e93e5d70e
  subdirs:
    - Spock
    - Spock-core
    - reroute
extra-deps:
- heist-1.0.1.0
- map-syntax-0.2.0.2
- snap-1.0.0.2
- xmlhtml-0.2.5
resolver: lts-9.3
